version: '3.1'

networks:
  zabbix-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.6.0/24
          gateway: 172.28.6.254
services:
  zabbix-mysql:
    container_name: zabbix-mysql
    image: mysql:8.0
    networks:
      zabbix-net:
        ipv4_address: 172.28.6.1
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    command: --character-set-server=utf8 --collation-server=utf8_bin
    environment:
      - MYSQL_ROOT_PASSWORD=root@pw
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix@pw

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-6.0.1
    networks:
      zabbix-net:
        ipv4_address: 172.28.6.2
    hostname: zbxserver
    links:
      - zabbix-mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix@pw
    depends_on:
      - zabbix-mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-6.0.1
    networks:
      zabbix-net:
        ipv4_address: 172.28.6.3
    hostname: zabbix
    links:
      - zabbix-mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=zabbix-mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix@pw
      - PHP_TZ=America/Sao_Paulo
      - ZBX_SERVER_HOST=zbxserver
      - ZBX_SERVER_NAME=Zabbix
    depends_on:
      - zabbix-mysql
   
  grafana:
    container_name: grafana2
    image: grafana/grafana
    networks:
      zabbix-net:
        ipv4_address: 172.28.6.4
    links:
      - zabbix-mysql
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - zabbix-mysql
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-6.0.1
    user: root
    networks:
      zabbix-net:
        ipv4_address: 172.28.6.5
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - ZBX_SERVER_HOST=172.28.6.2
    